sonar.projectKey=pedrolongooo_stockflow
sonar.organization=pedrolongooo

sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,.git/**,.github/**

sonar.sourceEncoding=UTF-8
