name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarcloud:
    name: Análise Estática com SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Executar análise SonarCloud
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
